version: '3.1'
services:
  db:
    image: mysql:8.0.26
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /root/secret
    volumes:
      - ./conf.d:/etc/mysql/conf.d
      - ./mysql:/var/lib/mysql
      - ./secret:/root/secret
